// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSchedule.Context;

#nullable disable

namespace SchoolSchedule.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260207123950_TestDb")]
    partial class TestDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolSchedule.Entites.AcademicClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CuratorTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Shift")
                        .HasColumnType("int");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuratorTeacherId")
                        .IsUnique()
                        .HasFilter("[CuratorTeacherId] IS NOT NULL");

                    b.ToTable("AcademicClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CuratorTeacherId = 1,
                            Name = "11-А",
                            Shift = 1,
                            StudentCount = 25
                        },
                        new
                        {
                            Id = 2,
                            CuratorTeacherId = 2,
                            Name = "9-Б",
                            Shift = 2,
                            StudentCount = 28
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Number = "101",
                            Type = "Обычный"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            Number = "202",
                            Type = "Компьютерный"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 60,
                            Number = "Спортзал",
                            Type = "Спортзал"
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("LessonIndex")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("AcademicClassId", "DayOfWeek", "LessonIndex")
                        .IsUnique();

                    b.HasIndex("ClassroomId", "DayOfWeek", "LessonIndex")
                        .IsUnique()
                        .HasFilter("[ClassroomId] IS NOT NULL");

                    b.HasIndex("TeacherId", "DayOfWeek", "LessonIndex")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Математика"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Русский язык"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Информатика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Физкультура"
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Петров Петр Петрович",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Сидорова Анна Ивановна",
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicClassId = null,
                            FullName = "Системный Администратор",
                            Password = "admin",
                            Role = 0,
                            TeacherId = null,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AcademicClassId = null,
                            FullName = "Петров Петр Петрович",
                            Password = "teacher1",
                            Role = 1,
                            TeacherId = 1,
                            Username = "teacher1"
                        },
                        new
                        {
                            Id = 3,
                            AcademicClassId = 1,
                            FullName = "Ученик 11-А",
                            Password = "student1",
                            Role = 2,
                            TeacherId = null,
                            Username = "student1"
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Workload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicClassId")
                        .HasColumnType("int");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Workloads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcademicClassId = 1,
                            HoursPerWeek = 5,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            AcademicClassId = 1,
                            HoursPerWeek = 3,
                            SubjectId = 2,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            AcademicClassId = 2,
                            HoursPerWeek = 4,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 4,
                            AcademicClassId = 2,
                            HoursPerWeek = 3,
                            SubjectId = 2,
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("SchoolSchedule.Entites.AcademicClass", b =>
                {
                    b.HasOne("SchoolSchedule.Entites.Teacher", "CuratorTeacher")
                        .WithMany()
                        .HasForeignKey("CuratorTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CuratorTeacher");
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Lesson", b =>
                {
                    b.HasOne("SchoolSchedule.Entites.AcademicClass", "AcademicClass")
                        .WithMany()
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Entites.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId");

                    b.HasOne("SchoolSchedule.Entites.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Entites.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicClass");

                    b.Navigation("Classroom");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Teacher", b =>
                {
                    b.HasOne("SchoolSchedule.Entites.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolSchedule.Entites.User", b =>
                {
                    b.HasOne("SchoolSchedule.Entites.AcademicClass", "AcademicClass")
                        .WithMany()
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolSchedule.Entites.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AcademicClass");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Workload", b =>
                {
                    b.HasOne("SchoolSchedule.Entites.AcademicClass", "AcademicClass")
                        .WithMany("Workloads")
                        .HasForeignKey("AcademicClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Entites.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSchedule.Entites.Teacher", "Teacher")
                        .WithMany("Workloads")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicClass");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSchedule.Entites.AcademicClass", b =>
                {
                    b.Navigation("Workloads");
                });

            modelBuilder.Entity("SchoolSchedule.Entites.Teacher", b =>
                {
                    b.Navigation("Workloads");
                });
#pragma warning restore 612, 618
        }
    }
}
